version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8080:8000"
    environment:
      - DB_ENGINE=django.db.backends.sqlite3
      - DB_NAME=/data/db.sqlite3
    volumes:
      - .:/app

